services:
  # flask service
  backend:
    container_name: yt_downloader_backend
    image: yt_downloader_backend:1.5.2
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CLOUDINARY_API_KEY=API_KEY
      - CLOUDINARY_API_SECRET=API_SECRET
      - CLOUDINARY_CLOUD_NAME=CLOUD_NAME
      - APP_SECRET_KEY=SECRET_KEY
    ports:
      - 8000:8000
